services:
  - type: web
    name: export-divisas-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SUPERADMIN_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: https://export-divisas.onrender.com
      - key: APP_URL
        value: https://export-divisas.onrender.com
